use chrono::{Date, DateTime, Local};

pub struct Movie {
    movie: String,
    year: u8,
    production_budget: u64,
    domestic_gross: u64,
    foreign_gross: u64,
    worldwide_gross: u64,
    month: u8,
    profit: i64,
    profit_margin: f64,
    roi: f64,
    pct_foreign: f64,
    match_key: String,
    popularity: f64,
    release_date: DateTime<Local>,
    original_language: String,
    vote_average: f64,
    vote_count: u64,
    genre_list: Vec<String>,
    genres: String,
    action: bool,
    adventure: bool,
    animation: bool,
    comedy: bool,
    crime: bool,
    documentary: bool,
    drama: bool,
    family: bool,
    fantasy: bool,
    history: bool,
    horror: bool,
    music: bool,
    mystery: bool,
    romance: bool,
    science_fiction: bool,
    tv_movie: bool,
    thriller: bool,
    war: bool,
    western: bool,
}
